# Generated by Django 2.2.3 on 2019-07-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSE_Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Name', max_length=20)),
                ('designation', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(blank=True, help_text='Enter a working E-Mail address', max_length=64, null=True)),
                ('number', models.CharField(blank=True, max_length=64, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('areas_of_interest', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('url', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
