# Generated by Django 2.2.3 on 2019-07-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_cse_year_of_joining'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cse',
            options={'verbose_name_plural': 'CSE'},
        ),
        migrations.AlterModelOptions(
            name='ece',
            options={'verbose_name_plural': 'ECE'},
        ),
        migrations.AlterField(
            model_name='cse',
            name='year_of_joining',
            field=models.CharField(choices=[('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2021', '2021')], default=2017, max_length=2),
        ),
    ]
