# Generated by Django 2.2.3 on 2019-07-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subpages', '0003_subpagecontent2_subpagecontent3'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpagecontent',
            name='title1',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
