# Generated by Django 2.2.3 on 2019-07-23 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subpages', '0004_subpagecontent_title1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subpagecontent',
            old_name='title1',
            new_name='url',
        ),
    ]
