# Generated by Django 2.2.3 on 2019-07-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subpages', '0007_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
