# Generated by Django 2.2.3 on 2019-07-26 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subpages', '0009_cse_faculty_ece_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ece_faculty',
            old_name='content',
            new_name='area_of_interest',
        ),
    ]
