# Generated by Django 2.2.3 on 2019-07-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subpages', '0010_auto_20190726_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cse_faculty',
            old_name='content',
            new_name='areas_of_interest',
        ),
        migrations.RenameField(
            model_name='ece_faculty',
            old_name='area_of_interest',
            new_name='areas_of_interest',
        ),
        migrations.AddField(
            model_name='cse_faculty',
            name='designation',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='cse_faculty',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cse_faculty',
            name='number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='ece_faculty',
            name='designation',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='ece_faculty',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ece_faculty',
            name='number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
