# Generated by Django 2.2.3 on 2019-07-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subpages', '0011_auto_20190726_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='cse_faculty',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='ece_faculty',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
