# Generated by Django 2.2.3 on 2019-07-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subpages', '0012_auto_20190727_0503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSE_Faculty',
        ),
        migrations.DeleteModel(
            name='ECE_Faculty',
        ),
    ]
