# Generated by Django 2.2.3 on 2019-07-29 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subpages', '0013_auto_20190727_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content_with_1_image',
            options={'verbose_name_plural': 'Content with 1 Image'},
        ),
        migrations.AlterModelOptions(
            name='content_with_2_image',
            options={'verbose_name_plural': 'Content with 2 Image'},
        ),
        migrations.AlterModelOptions(
            name='content_with_3_image',
            options={'verbose_name_plural': 'Content with 3 Image'},
        ),
    ]
